name: Check if the user is collaborator of the current repository
inputs:
  username:
    description: "The username to get."
    required: true
  github-token:
    description: "the GITHUB_TOKEN secret."
    required: true
outputs:
  is_collaborator:
    description: "Whether the user is collaborator or not"
    value: ${{ steps.check-collaborator.outputs.status == '204' }}
runs:
  using: "composite"
  steps:
    - env:
        USERNAME: "${{ inputs.username }}"
        GITHUB_TOKEN: "${{ inputs.github-token }}"
      shell: bash --noprofile --norc -euo pipefail {0}
      id: check-collaborator
      run: |
        echo -n "::set-output name=status::"
        curl -s -w '%{http_code}' -o /dev/null \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          "https://api.github.com/repos/${{ github.repository }}/collaborators/$USERNAME"
